### ISSUE TITLE
Conceptos y fases de gestión de proyectos de software

### ISSUE THREAD

**Issue by dulce-blm** [SistemasTecTlaxiaco/infografia-dulce-blm-1#2]
![Conceptos y fases de gestión de proyectos de software](https://user-images.githubusercontent.com/72100538/132162770-c295cf05-f5db-4938-b84a-372475697b23.png)

**Comment by Graciela2000** [comment]
Calificación: 20 %
Calificó: Graciela Hernández Santiago

**Comment by josealfredo79** [comment]
Bien hecho y revisado
